/*
 * cek.h — Lark C CEK machine: types and public API.
 *
 * Memory model
 * ------------
 * All runtime allocations (closures, tuples, constructors, strings) come
 * from a single bump-pointer arena.  Nothing is freed individually; the
 * arena is released after the program finishes.  This matches the program's
 * single-execution lifetime and keeps allocation O(1).
 *
 * AST types (LkExpr, LkPat, LkArm, LkDecl, LkProg) are read-only and live
 * in static storage — they are generated by emit_c_ast.py and never written
 * at runtime.
 *
 * Value representation
 * --------------------
 * LkVal is a tagged 12-byte (32-bit) or 16-byte (64-bit) struct that is
 * passed by value.  Primitives (int, float, bool, unit, IO) are stored
 * inline.  Heap objects (str, tuple, con, partial, closure) are stored as
 * pointers to arena-allocated records that use flexible array members so
 * that the header and fields occupy a single contiguous allocation.
 */

#pragma once
#include <stddef.h>
#include <stdint.h>


/* -- Arena -- */

typedef struct {
    char*  base;
    size_t cap;
    size_t used;
} LkArena;

/* Allocate `bytes` from the arena, aligned to 8 bytes.  Aborts on overflow. */
void* arena_alloc(LkArena* a, size_t bytes);


/* -- Forward declarations -- */

typedef struct LkExpr    LkExpr;
typedef struct LkPat     LkPat;
typedef struct LkArm     LkArm;
typedef struct LkDecl    LkDecl;
typedef struct LkVal     LkVal;
typedef struct LkEnv     LkEnv;
typedef struct LkTuple   LkTuple;
typedef struct LkCon     LkCon;
typedef struct LkPartCon LkPartCon;
typedef struct LkClosure LkClosure;


/* -- AST: Literals -- */

typedef enum { LIT_INT, LIT_FLOAT, LIT_BOOL, LIT_STR, LIT_UNIT } LitKind;

typedef struct {
    LitKind kind;
    union {
        int32_t     i;
        uint32_t    f;   /* IEEE 754 float32 bits */
        int         b;
        const char* s;
    };
} LkLit;


/* -- AST: Expressions -- */

typedef enum {
    EXPR_LIT,
    EXPR_VAR,    /* variable reference */
    EXPR_CON,    /* constructor reference */
    EXPR_TUPLE,
    EXPR_APPLY,  /* curried application, n_args >= 1 */
    EXPR_BINOP,
    EXPR_UNARY,
    EXPR_LET,
    EXPR_IF,
    EXPR_MATCH,
    EXPR_LAMBDA, /* always single-param; multi-param fns are nested lambdas */
} ExprKind;

struct LkExpr {
    ExprKind kind;
    union {
        LkLit             lit;

        const char*       name;                    /* EXPR_VAR, EXPR_CON */

        struct {                                   /* EXPR_TUPLE */
            const LkExpr* const* elems;
            int                  n;
        } tup;

        struct {                                   /* EXPR_APPLY */
            const LkExpr*        fn;
            const LkExpr* const* args;
            int                  n_args;
        } app;

        struct {                                   /* EXPR_BINOP */
            const char*   op;
            const LkExpr* left;
            const LkExpr* right;
        } binop;

        struct {                                   /* EXPR_UNARY */
            const char*   op;
            const LkExpr* operand;
        } unary;

        struct {                                   /* EXPR_LET */
            const char*   name;
            const LkExpr* val;
            const LkExpr* body;
        } let;

        struct {                                   /* EXPR_IF */
            const LkExpr* cond;
            const LkExpr* then_;
            const LkExpr* else_;
        } if_;

        struct {                                   /* EXPR_MATCH */
            const LkExpr* scrutinee;
            const LkArm*  arms;
            int           n_arms;
        } match;

        struct {                                   /* EXPR_LAMBDA */
            const char*   param;
            const LkExpr* body;
        } lam;
    };
};


/* -- AST: Patterns -- */

typedef enum { PAT_WILD, PAT_VAR, PAT_LIT, PAT_CON, PAT_TUPLE } PatKind;

struct LkPat {
    PatKind kind;
    union {
        const char* var;                         /* PAT_VAR */

        LkLit       lit;                         /* PAT_LIT */

        struct {                                 /* PAT_CON */
            const char*        name;
            const LkPat* const* args;
            int                 n_args;
        } con;

        struct {                                 /* PAT_TUPLE */
            const LkPat* const* elems;
            int                 n;
        } tup;
    };
};

struct LkArm {
    const LkPat*  pat;
    const LkExpr* body;
};


/* -- AST: Declarations -- */

typedef enum { DECL_FN, DECL_LET, DECL_TYPE, DECL_IMPL } DeclKind;

typedef struct { const char* name; int arity; } LkVariant;

typedef struct {
    const char*   name;
    const char*   param;   /* single param; multi-param fns desugared to lambdas */
    const LkExpr* body;
} LkMethod;

struct LkDecl {
    DeclKind    kind;
    const char* name;
    union {
        struct {                                 /* DECL_FN */
            const char*   param;
            const LkExpr* body;
        } fn;

        const LkExpr* let_val;                   /* DECL_LET */

        struct {                                 /* DECL_TYPE */
            const LkVariant* variants;
            int              n_variants;
        } type_;

        struct {                                 /* DECL_IMPL */
            const char*      trait_name;
            const LkMethod*  methods;
            int              n_methods;
        } impl;
    };
};

typedef struct {
    const LkDecl* const* decls;   /* pointer to array of const LkDecl* */
    int                  n_decls;
} LkProg;


/* -- Runtime: Values -- */

/*
 * LkVal is defined before the heap-object structs because LkTuple, LkCon,
 * and LkPartCon use LkVal as a flexible array member (which requires the
 * complete type).  LkTuple*, LkCon*, LkPartCon*, LkClosure* inside LkVal
 * are only pointers, so forward declarations suffice there.
 */

typedef enum {
    V_INT, V_FLOAT, V_BOOL, V_STR, V_UNIT,
    V_TUPLE, V_CON, V_PARTIAL,
    V_CLOSURE, V_BUILTIN, V_PRINT_IO, V_DISPATCH, V_IO,
} ValKind;

struct LkVal {
    ValKind kind;
    union {
        int32_t      i;
        uint32_t     f;       /* IEEE 754 float32 bits */
        int          b;
        const char*  s;       /* V_STR: arena-allocated or string literal */
        LkTuple*     tup;
        LkCon*       con;
        LkPartCon*   part;
        LkClosure*   clos;
        const char*  builtin; /* V_BUILTIN: name in builtin table */
        LkVal*       pio;     /* V_PRINT_IO: pointer to the IO value */
        const char*  method;  /* V_DISPATCH: method name */
        /* V_UNIT, V_IO: no payload */
    };
};


/* -- Runtime: Heap objects (flexible array members) -- */

/*
 * All heap objects are allocated from the arena with one arena_alloc call
 * that covers the header and the inline element array.  LkVal must be
 * complete before these definitions.
 */

struct LkTuple {
    int   n;
    LkVal elems[];   /* n elements inline */
};

struct LkCon {
    const char* tag;
    int         n;
    LkVal       fields[];   /* n fields inline */
};

struct LkPartCon {
    const char* tag;
    int         arity;
    int         n;
    LkVal       args[];   /* n args applied so far */
};

struct LkClosure {
    const char*   param;
    const LkExpr* body;
    LkEnv*        env;
    const char*   rec;   /* name to rebind for self-reference; NULL if none */
};


/* -- Runtime: Environment -- */

/*
 * Environments are persistent linked lists.  env_bind creates a new cell in
 * the arena.  Closures capture a pointer to their creation-site environment.
 * Top-level names are kept separately (see cek.c) and checked after the
 * local chain, avoiding the need to backpatch closure envs.
 */
struct LkEnv {
    const char* name;
    LkVal       val;
    LkEnv*      next;
};


/* -- Runtime: Continuation frames -- */

typedef enum {
    FRAME_APPLY_FN,    /* evaluating the function position of an application */
    FRAME_APPLY_ARG,   /* evaluating arguments one by one */
    FRAME_LET,
    FRAME_IF,
    FRAME_MATCH,
    FRAME_BINOP_L,     /* evaluating left operand */
    FRAME_BINOP_R,     /* evaluating right operand, left already done */
    FRAME_UNARY,
    FRAME_TUPLE,       /* building a tuple element by element */
} FrameKind;

typedef struct {
    FrameKind kind;
    LkEnv*    env;     /* environment at the time the frame was pushed */
    union {
        struct {
            const LkExpr* const* args;
            int                  n_args;
        } apply_fn;

        struct {
            LkVal                fn_val;
            const LkExpr* const* remaining;
            int                  n_remaining;
        } apply_arg;

        struct {
            const char*   name;
            const LkExpr* body;
        } let;

        struct {
            const LkExpr* then_;
            const LkExpr* else_;
        } if_;

        struct {
            const LkArm* arms;
            int          n_arms;
        } match;

        struct {
            const char*   op;
            const LkExpr* right;
        } binop_l;

        struct {
            const char* op;
            LkVal       left;
        } binop_r;

        struct {
            const char* op;
        } unary;

        struct {
            const LkExpr* const* remaining;
            int                  n_remaining;
            LkTuple*             tup;    /* pre-allocated LkTuple (header+FAM); filled in-place */
            int                  n_done;
        } tuple;
    };
} LkFrame;


/* -- CEK API -- */

/*
 * Run a Lark program from its statically-generated AST.
 * Calls main(io) and returns after the program completes.
 */
void cek_run(const LkProg* prog);
