/*
 * larkrun.c — driver for the Lark C CEK interpreter.
 *
 * This file is compiled together with cek.c and a program-specific
 * prog_ast.c (generated by emit_c_ast.py) to produce a standalone binary.
 *
 * On Pico 2W the `main` below replaces lark_entry.c; all I/O still goes
 * through the platform layer in platform_pico.c / platform_posix.c.
 */

#include "cek.h"

/* Defined in the generated prog_ast.c */
extern LkProg lk_program;

int main(void) {
    cek_run(&lk_program);
    return 0;
}
